language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo" UNIT_TEST=1
  - VERSION="7.0" ODOO_REPO="OCA/OCB" UNIT_TEST=1

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/OCA/product-attribute $HOME/product-attribute -b ${VERSION}
  - git clone https://github.com/OCA/purchase-workflow $HOME/purchase-workflow -b ${VERSION}
  - git clone https://github.com/OCA/server-tools.git $HOME/server-tools -b ${VERSION}

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
